apiVersion: v1
kind: Service
metadata:
  name: tiacloud-service
  namespace: tiacourses
spec:
  selector:
    app: tiacloud
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
  type: ClusterIP
